version: '3.8'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=kittygram
      - POSTGRES_USER=kittygram_user
      - POSTGRES_PASSWORD=kittygram_password
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: mrsunstrike/kittygram_backend
    environment:
      - POSTGRES_DB=kittygram
      - POSTGRES_USER=kittygram_user
      - POSTGRES_PASSWORD=kittygram_password
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - static_volume:/backend_static
      - media_volume:/media
  frontend:
    image: mrsunstrike/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: mrsunstrike/kittygram_gateway
    volumes:
      - static_volume:/staticfiles
      - media_volume:/media
    ports:
      - 9000:80
